const elementId = {
  Homepage: {
    GlobalHeader: {
      IconLogoSeva: 'icon-logo-seva',
      IconCitySelector: 'icon-loc-header',
      IconSearch: 'icon-search-header',
      NavigationMenu: 'navigation-menu',
      HamburgerMenu: 'hamburger-menu',
      ChangeLocation: 'change-location',
      PopupChangeLocation: 'change-location-header-',
      DropdownListCity: 'city-selector-',
      ButtonNantiSaja: 'button-nanti-saja-city',
      ButtonMulaiCariMobil: 'button-mulai-cari-mobil',
      FieldInputCity: 'field-input-city',
    },
    CarSearchWidget: {
      DropdownDp: 'dropdown-dp',
      DpOption: 'dp-option-',
      TenorOption: 'tenor-option-',
      InputPhoneNumber: 'input-phone-number',
      AdvanceSearch: 'advance-search',
      DropdownIncomeRange: 'dropdown-kisaran-pendapatan',
      DropdownAgeRange: 'dropdown-rentang-usia',
      ButtonFindCar: 'button-temukan-mobil',
      ErrorMessageDP: 'field-message-error-dp',
      ErrorMessageIncome: 'field-message-error-income',
      ErrorMessageAge: 'field-message-error-age',
    },
    Button: {
      CekKK: 'button-check-kualifikasi-kredit',
      TambahFilterFinansial: 'button-tambah-filter-finansial',
      CariMobil: 'button-cari-mobil',
      PromoEkslusif: 'button-promo-ekslusif',
      LihatRincian: 'button-lihat-rincian',
      LihatPenawaran: 'button-lihat-penawaran',
      LebihLanjut: {
        TukarTambah: 'button-pelajari-lebih-lanjut-tukar-tambah',
        Refi: 'button-pelajari-lebih-lanjut-refi',
        LayananKendaraan: 'button-pelajari-lebih-lanjut-layanan-kendaraan',
      },
    },
    Dropdown: {
      KategoriUmur: 'dropdown-kategori-umur',
    },
    Promo: {
      LihatSemua: 'lihat-semua-promo',
      DetailPromo: 'lihat-detail-promo',
    },
    PilihMobilImpian: 'pilih-mobil-impian',
    HitungKemampuan: 'hitung-kemampuan',
    KualifikasiKredit: 'kualifikasi-kredit',
    CarOfMonth: 'seva-car-of-month',
    LayananLainSeva: 'layanan-lain-dari-SEVA',
    HomePageBanner: 'homepage-banner-',
    TopNewCar: 'icon-',
    CitySelectorPopup: {
      InputCitySelectorKTP: 'header-input-city-selector-ktp',
      ChooseCityPopup: 'city-recomendation-',
      ListCityPopup: 'city-search-',
    },
    SearchBar: {
      InputSearchCar: 'header-input-search-car',
      CarModelOption: 'header-car-model-option-',
    },
    CarOfTheMonth: {
      ListBrand: 'car-of-the-month-',
    },
    HeaderMenu: {
      BuyCarMenu: 'header-menu-beli-mobil',
      Other: 'header-menu-',
      SubMenu: 'sub-menu-',
    },
    BuyCar: 'brand-',
    TypeNewCar: 'tipe-',
    ContactAgent: {
      FullName: 'agen-nama-lengkap',
      PhoneNumber: 'agen-nomor-telepon',
      ButtonSend: 'agen-submit-kirim-rincian-homepage',
    },
    Article: {
      SeeAllButton: 'button-lihat-semua-artikel',
      ButtonCategory: '-artikel-button',
      LabelLink: 'label-link-name-kategori-',
      Tab: 'tab-',
    },
  },
  Modal: {
    login: 'button-masuk-popup',
  },
  Footer: {
    MenuLink: 'footer-',
    DescriptionLink: 'text-footer-about-seva',
    TentangKami: 'footer-tentang-kami',
    SyaratKetentuan: 'footer-syarat-ketentuan',
    KebijakanPrivasi: 'footer-kebijakan-privasi',
    HubungiKami: 'footer-hubungi-kami',
    LogoFacebook: 'footer-logo-facebook',
    LogoTwitter: 'footer-logo-twitter',
    LogoInstagram: 'footer-logo-instagram',
    LogoYoutube: 'footer-logo-youtube',
    LogoLinkedin: 'footer-logo-linkedin',
    TextAboutSeva: 'text-about-seva',
    LogoISO: 'logo-iso',
  },
  HamburgerMenu: {
    SidebarMobileWeb: {
      ButtonLoginRegister: 'button-burger-menu-menu-masuk-atau-daftar',
      BuyCar: 'menu-beli-mobil',
      Refinancing: 'menu-fasilitas-dana',
      EDoc: 'menu-layanan-surat-kendaraan',
      TemanSeva: 'menu-teman-seva',
      Promo: 'menu-promo',
      Article: 'menu-article',
      AboutSeva: 'menu-tentang-seva',
      Other: 'menu-lainyya',
    },
    Login: {
      ButtonNext: 'button-selanjutnya',
      InputPhoneNumber: 'text-login-no-tlp-login',
      InputOTP: 'text-login-otp-login',
      WrongOTP: 'text-otp-salah-login',
      LoginNow: 'button-login',
      RegisterInput: 'button-masuk',
    },
    Register: {
      RegisterNow: 'daftar-sekarang',
      InputPhoneNumber: 'text-login-no-tlp-daftar',
      FullName: 'nama-lengkap-daftar',
      Email: 'email-daftar',
      DropdownGender: 'dropdown-gender-daftar',
      DropdownMaritalStatus: 'dropdown-marital-status',
      BirthDate: 'birth-date-daftar',
      CheckboxInformation: 'checkbox-informasi-promo-daftar',
      CheckboxTnC: 'checkbox-setuju-syarat-ketentuan-daftar',
      ButtonNext: 'button-selanjutnya-register',
    },
  },
  CarResultPage: {
    ButtonSearch: 'button-atur-pencarian',
    TotalCar: 'text-jumlah-mobil',
    CarImage: 'car-image-',
    HeaderCityResult: 'text-header-city-result',
    CarModel: 'car-model-',
    CarPrice: 'car-price-',
    Installment: 'car-monthly-installment',
    DP: 'car-dp',
    Tenor: 'car-tenor-',
    ButtonOffer: 'button-minta-penawaran',
  },
  DSOCityBlocker: 'text-DSO-city-blocker',
  CarImage: 'car-image',
  HeroImage: 'hero-image',
  MainPicture: 'main-picture',
  CarouselPicture: 'carousel-picture',
  Logo: 'logo-',
  Type: 'type-',
  Text: 'text-',
  Tab: 'tab-',
  Button: 'button-',
  FilterMerek: 'filter-merek',
  FilterType: 'filter-type',
  FilterHarga: 'filter-harga',
  FieldMinPrice: 'field-min-price',
  FieldMaxPrice: 'field-max-price',
  FilterBrand: 'filter-brand-',
  FilterTypeCar: 'filter-tipe-',
  FilterMaxDP: 'filter-dp-',
  FilterAgeRate: 'filter-usia-',
  FilterIncomeRate: 'filter-pendapatan-',
  FilterPriceRange: 'filter-urutkan-',
  FilterButton: {
    Submit: 'button-terapkan',
    Delete: 'button-hapus-filter',
    Reset: 'button-atur-ulang',
    Sorting: 'button-sorting-harga',
  },
  DatePicker: {
    DOB: 'date-picker-tanggal-lahir',
  },
  Dropdown: {
    Gender: 'dropdown-jenis-kelamin',
  },
  Field: {
    DP: 'field-input-dp',
    DPPercentage: 'field-input-dp-percentage',
    Tenure: 'field-input-tenor',
    TenurePopup: 'field-pilih-',
    Income: 'field-input-pendapatan',
    Age: 'field-pilih-kategori-umur-',
    FullName: 'field-input-nama-lengkap',
    PhoneNumber: 'field-input-nomor-hp',
    Sorting: 'field-pilih-sorting-',
    CarMobil: 'field-car-mobil',
    ADDM: 'field-addm',
    ADDB: 'field-addb',
    Promo: 'field-input-promo',
  },
  Input: {
    FullName: 'input-nama-lengkap',
    PhoneNumber: 'input-phone-number',
    TanggalLahir: 'input-tanggal-lahir',
    KodeReferral: 'input-kode-referral',
    Email: 'input-email',
    OTP: 'input-otp',
    NIK: 'input-nik',
    Name: 'input-nama',
    Address: 'input-alamat',
    RTRW: 'input-rt-rw',
    KelurahanDesa: 'input-kelurahan-desa',
    Kecamatan: 'input-kecamatan',
  },
  Refinancing: {
    ButtonApplyNow: 'button-ajukan-sekarang',
    RequiredDocument: 'dokumen-yang-dibutuhkan',
    DiscussSeva: 'seva-diskusi',
    FullName: 'input-nama-lengkap-refi',
    PhoneNumber: 'input-nomor-handphone-refi',
    ButtonSend: 'button-kirim',
  },
  InstantApproval: {
    FindCreditCar: 'cari-mobil-kredit',
    ButtonCalculateInstallment: 'button-hitung-cicilan',
    ButtonOffer: 'button-minta-penawaran-ia',
    PopupName: 'nama-lengkap-ia',
    PopupPn: 'nomor-handphone-ia',
    CheckboxWA: 'checkbox-setuju-kirim-whatsapp',
    ButtonSendDetails: 'button-kirim-rincian',
    ButtonApplyIA: 'button-ajukan-instant-approval',
    MonthlyIncome: 'pendapatan-perbulan',
    DropdownAge: 'dropdown-umur',
    InputDP: 'input-masukan-dp',
    ButtonPaidInAdvance: 'button-dibayar-diawal',
    ButtonPaidEnd: 'button-dibayar-diakhir',
  },
  PLP: {
    Button: {
      HitungKemampuan: 'button-hitung-kemampuan-plp',
      FilterMobil: 'button-filter-mobil-plp',
      Promo: 'button-promo',
      LihatSNK: 'button-lihat-snk',
      LihatDetail: 'button-lihat-detail',
      LeadsFormIcon: 'button-leads-from-icon',
      KirimLeads: 'button-kirim-leads',
      UbahLokasi: 'button-ubah-lokasi',
    },
    Text: {
      Text: 'text-',
      JumlahMobil: 'text-jumlah-mobil-plp',
      JudulPopupPromo: 'text-judul-popup-promo',
      SuccessToastMessageLeads: 'text-success-toast-message-leads',
      CarNotFound: 'text-car-not-found',
    },
    Close: {
      Button: {
        FilterPopup: 'close-button-filter-popup',
        PopupSorting: 'close-button-popup-sorting-harga',
        PopupPromo: 'close-button-popup-promo',
      },
    },
    Dropdown: {
      DetailMobil: 'dropdown-detail-mobil',
      FilterFinansial: 'dropdown-filter-finansial',
    },
    LeadsForm: {
      name: 'nama-lengkap-plp-leads',
      phone: 'nomor-telp-plp-leads',
      btnSend: 'submit-plp-leads',
      FullName: 'field-input-leads-nama-lengkap',
      PhoneNumber: 'field-input-leads-nomor-hp',
    },
  },
  CarRecommendation: {
    Image: 'image-car-recommendation',
    Button: {
      Promo: 'button-promo-car-recommendation',
      ClosePopupPromo: 'close-button-popup-promo-car-recommendation',
      LihatSNK: 'button-lihat-snk-car-recommendation',
      LihatDetail: 'button-lihat-detail-car-recommendation',
    },
    Judul: 'tex-judul-popup-promo-car-recommendation',
    BrandModel: 'text-brand-model-mobil-car-recommendation',
    NominalCicilan: 'text-nominal-cicilan-car-recommendation',
  },
  PDP: {
    VideoUlasan: 'video-ulasan',
    LeadsForm: {
      name: 'nama-lengkap-pdp-leads',
      phone: 'nomor-telp-pdp-leads',
      btnSend: 'submit-pdp-leads',
    },
    NavigationTab: {
      V1: 'navigation-tab-v1',
      V2: 'navigation-tab-v2',
    },
    WarnaTab: {
      ColorSelector: 'warna-tab-color-selector',
      ColorSelectorLeftArrow: 'warna-tab-color-selector-left-arrow',
      ColorSelectorRightArrow: 'warna-tab-color-selector-right-arrow',
    },
    CarOverview: {
      CityOtr: 'car-overview-city-otr',
      CityToolTip: 'car-overview-city-tooltip',
      DownloadBrochure: 'car-overview-download-brochure',
      CtaCalculate: 'car-overview-cta-calculate',
      ShareButton: 'car-overview-share-button',
      Cicilan: 'car-overview-cicilan-value',
      DPValue: 'car-overview-dp-value',
      TenorValue: 'car-overvoew-tenor-value',
    },
    FloatingWhatsapp: 'pdp-floating-whatsapp',
    VideoTab: {
      VideoIframe: 'video-tab-content',
    },
    RingkasanTab: {
      VideoSection: {
        Card: 'ringkasan-tab-video-card',
        Thumbnail: 'ringkasan-tab-video-thumbnail',
      },
    },
    ShareModal: {
      Container: 'share-modal-container',
      Facebook: 'share-modal-item-facebook',
      Whatsapp: 'share-modal-item-whatsapp',
      Twitter: 'share-modal-item-twitter',
      Copy: 'share-modal-item-copy',
    },
    OTR: {
      Widget: {
        CTACitySelector: 'otr-widget-cta-city-selector',
        Price: 'otr-widget-teks-otr-price',
      },
    },
    CTA: {
      UnduhBrosur: 'cta-unduh-brosur',
      Popup: {
        Facebook: 'cta-facebook-pop-up-share',
        Twitter: 'cta-twitter-pop-up-share',
        WA: 'cta-wa-pop-up-share',
        CopyLink: 'cta-copy-link-pop-up-share',
      },
      LihatDetail: 'cta-lihat-detail',
      LihatSemuaPromo: 'cta-lihat-semua-promo',
      LihatDetailPromo: 'cta-lihat-detail-promo',
      LihatVarian: 'cta-lihat-varian',
      BacaSelengkapnya: 'cta-baca-selengkapnya',
    },
    Drowpdown: {
      PilihKota: 'dropdown-pilih-kota',
      CarVariant: 'dropdown-car-variant',
    },
    Button: {
      Grid: 'button-grid-view',
      List: 'button-list-view',
      HitungKemampuan: 'button-hitung-kemampuan',
      Share: 'button-share',
      Close: {
        PopupShare: 'button-close-popup-share',
      },
      NextMainPicture: 'button-next-main-picture',
      PreviousMainPicture: 'button-previous-main-picture',
      FocusMode: 'button-focus-mode',
      NextCarouselPicture: 'button-next-carousel-picture',
      PreviousCarouselPicture: 'button-previous-carousel-picture',
      CariMobil: 'button-cari-mobil',
    },
    Grid: {
      VariantCard: 'grid-view-variant-card',
      VariantDetail: 'grid-view-variant-detail',
      VariantName: 'grid-view-variant-name',
      VariantPrice: 'grid-view-variant-price',
      CTAHitungKemampuan: 'grid-view-cta-hitung-kemampuan',
    },
    List: {
      VariantCard: 'list-view-variant-card',
      VariantDetail: 'list-view-variant-detail',
      VariantName: 'list-view-variant-name',
      VariantPrice: 'list-view-variant-price',
      CTAHitungKemampuan: 'list-view-cta-hitung-kemampuan',
    },
    FAQ: {
      CicilanMobil: 'faq-cicilan-mobil',
      HargaMobil: 'faq-harga-mobil',
      PanjangMobil: 'faq-panjang-mobil',
      KapasitasMobil: 'faq-kapasitas-mobil',
      TransmisiMobil: 'faq-transmisi-mobil',
    },
  },
  LoanCalculator: {
    SliderDP: 'slider-DP',
    RekomendasiFinansial: 'rekomendasi-sesuai-kemampuan-finansial',
    Popup: {
      KualifikasiKredit: 'popup-info-kualifikasi-kredit',
    },
    Dropdown: {
      City: 'dropdown-city-selector-lc',
      Mobil: 'dropdown-mobil-lc',
      VariantMobil: 'dropdown-variant-mobil-lc',
    },
    Input: {
      Income: 'input-pendapatan-bulanan',
      DP: 'input-kemampuan-DP',
      DPPercentage: 'input-percentage-DP',
      KodePromo: 'input-kode-promo',
    },
    Button: {
      ADDM: 'button-addm',
      ADDB: 'button-addb',
      Age: 'button-kategori-umur',
      HitungKemampuan: 'button-hitung-kemampuan-lc',
      PopupKualifikasiKredit: 'button-popup-kualifikasi-kredit',
      HubungiAgenSeva: 'button-hubungi-agen-seva',
      LihatDetail: 'button-lihat-detail',
    },
    Result: {
      LoanCalculator: 'result-loan-calculator',
    },
    Info: {
      OTRIcon: 'info-kota-OTR',
      KualifikasiKredit: 'info-kualifikasi-kredit',
    },
  },
  Profil: {
    PromoTersedia: 'image-promo-tersedia',
    CheckboxKTP: 'checkbox-persetujuan-ktp',
    ArrowBack: 'arrow-back',
    Dropdown: {
      Camera: 'dropdown-switch-camera',
      StatusPerkawinan: 'dropdown-status-perkawinan',
    },
    PromoWidget: {
      Box: 'box-promo-widget',
      Image: 'image-promo-widget',
      Text: 'text-promo-widget',
      Arrow: 'arrow-promo-widget',
    },
    Button: {
      SimpanPerubahan: 'button-simpan-perubahan',
      KeluarAkun: 'button-keluar-akun',
      Kembali: 'button-kembali',
      BatalkanPerubahan: 'button-batalkan-perubahan-dan-lanjutkan',
      Lanjutkan: 'button-lanjutkan',
      CaptureImage: 'button-capture-image',
      FotoUlang: 'button-foto-ulang',
      GunakanFotoIni: 'button-gunakan-foto-ini',
      Close: 'button-x',
      CobaLagi: 'button-coba-lagi',
      Konfirmasi: 'button-konfirmasi',
      CariMobilLain: 'button-cari-mobil-lain',
      LihatPromo: 'button-lihat-promo',
      PlayStore: 'button-play-store',
      AppStore: 'button-app-store',
      GantiKTP: 'button-ganti-ktp',
      FotoUlangPopup: 'button-foto-ulang-popup',
      KembaliAkun: 'button-kembali-ke-akun',
      CariMobil: 'button-cari-mobil',
    },
  },
  Login: {
    LogoSeva: 'login-image-logo-seva',
    HeaderText: 'login-header-text',
    DescriptionText: 'login-description-text',
    DescriptionFooter: 'description-footer',
    Button: {
      Lanjutkan: 'button-lanjutkan',
      XOTP: 'button-x-popup-otp',
      Resend: 'button-resend-otp',
    },
    TitleTextOTP: 'title-text-popup-otp',
    SubtitleTextOTP: 'subtitle-text-popup-otp',
    TimerOTP: 'timer-popup-otp',
  },
  Register: {
    LogoSeva: 'register-image-logo-seva',
    HeaderText: 'register-header-text',
    DescriptionText: 'register-description-text',
    CheckBox: {
      SayaMau: 'checkbox-Ya, saya mau menerima informasi promo terbaru',
      Setuju:
        'checkbox-Saya setuju dengan Syarat & Ketentuan serta Kebijakan Privasi yang berlaku',
    },
    Button: {
      Daftar: 'button-daftar',
    },
    Link: {
      SNK: 'link-text-syarat&ketentuan',
      KebijakanPrivasi: 'link-text-kebijakan-privasi',
    },
  },
}

export default elementId
