import {
  PropsBrand,
  PropsCapsule,
  PropsIcon,
  PropsTypeCar,
  PropsAnnouncementBox,
  PropsArticle,
  PropsCategory,
  PropsHowToUse,
  PropsFloatingSection,
  PropsSearchMobile,
  PropsOffering,
  PropsContactUs,
  PropsSelectorList,
  PropsButtonTenure,
  PropsDetailList,
  PropsListNavBarMenu,
} from './props'

import {
  Location,
  Article,
  Banner,
  Car,
  CarDetail,
  Testimony,
  HowToUse,
  Variant,
  Form,
  FormWidget,
  Menu,
  UTMCollector,
} from './utils'

export type {
  PropsBrand,
  PropsCapsule,
  PropsIcon,
  PropsTypeCar,
  PropsAnnouncementBox,
  PropsHowToUse,
  PropsArticle,
  PropsCategory,
  PropsFloatingSection,
  PropsSearchMobile,
  PropsOffering,
  PropsContactUs,
  PropsSelectorList,
  PropsButtonTenure,
  PropsDetailList,
  PropsListNavBarMenu,
  Location,
  Article,
  Banner,
  Car,
  CarDetail,
  Testimony,
  HowToUse,
  Variant,
  Form,
  FormWidget,
  Menu,
  UTMCollector,
}
