export const rootUrl = '/'
export const carResultsUrl = '/mobil-baru'
export const loanCalculatorWithCityBrandModelVariantUrl =
  '/kalkulator-kredit/:cityName/:brand/:model/:variant'
export const variantListUrl = '/mobil-baru/:brand/:model/:tab?'
export const loanCalculatorDefaultUrl = '/kalkulator-kredit'
export const LoginSevaUrl = '/masuk-akun'
export const TemanSevaDashboardUrl = '/teman-seva/dashboard'
export const TemanSevaOnboardingUrl = '/teman-seva/onboarding'
export const preApprovalQuestionFlowUrl = '/pre-approval-question-flow'
