export const rootUrl = '/'
export const carResultsUrl = '/mobil-baru'
export const loanCalculatorWithCityBrandModelVariantUrl =
  '/kalkulator-kredit/:cityName/:brand/:model/:variant'
export const variantListUrl = '/mobil-baru/:brand/:model/:tab?'
export const loanCalculatorDefaultUrl = '/kalkulator-kredit'
export const loanCalculatorWithCityBrandModelUrl =
  '/kalkulator-kredit/:cityName/:brand/:model'
export const preApprovalStartUrl = '/pre-approval-start'
export const LoginSevaUrl = '/masuk-akun'
export const TemanSevaDashboardUrl = '/teman-seva/dashboard'
export const TemanSevaOnboardingUrl = '/teman-seva/onboarding'
export const preApprovalQuestionFlowUrl = '/pre-approval-question-flow'
export const creditQualificationUrl = '/kualifikasi-kredit'
export const loginUrl = '/login'
export const SalesDashboardUrl = '/event/giias/sales-dashboard'
export const SalesDashboardPAUrl = '/sales-dashboard'
export const refinancingUrl = '/fasilitas-dana'
export const multiCreditQualificationPageUrl = '/kualifikasi-kredit/multi'
