import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Buttons } from '../components/atoms/'
import { Headers } from '../components/molecules'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.scss'
import axios from 'axios'
import { api } from '../services/api'

const Home = () => {
  const [dark, setDark] = useState(false)
  useEffect(() => {
    console.log('testing marcell')
    const data = {
      name: 'morpheus',
      job: 'zion resident',
    }
    api.getProduct().then()
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headers />
      <h1 className={`${dark ? 'light' : `${styles.expand}`}`}>testingggg</h1>
      <h2 className={`dark ${styles.expand}`}>Hello User </h2>
      <h1 className="test">testing </h1>
      <h1 className={styles.testing}>testing </h1>
      <button onClick={() => setDark(!dark)}>click</button>
      <Buttons />
    </>
  )
}

export default Home
